{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) .Values.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plagona-redis.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "plagona-redis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  redis-password: {{ printf "%v" .Values.auth.password | b64enc | quote }}
{{- end }}
